dist: trusty

sudo: false

php:
  - 7.1

matrix:
  fast_finish: true

  include:
    - language: php
      php: 7.1
      env: PHPCS=1
    - language: node_js
      node_js: 6
      env: JSLINT=1

before_script:
  - if [[ $PHPCS = 1 ]]; then composer require cakephp/cakephp-codesniffer:*; fi
  - if [[ $PHPCS != 1 ]]; then composer install; fi
  - if [[ $PHPCS != 1 ]]; then composer run-script post-install-cmd --no-interaction; fi

script:
  - if [[ $PHPCS != 1 ]]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi
  - if [[ $PHPCS != 1 ]]; then mkdir -p build/logs; fi
  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -p --extensions=php --error-severity=1 --warning-severity=0 --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./config ./webroot; fi
  - if [[ $JSLINT = 1 ]]; then npm run lint; fi

notifications:
  email: false
  slack: cber:ZeUxtjnpHNEYCkMtUBhskwXl

addons:
  code_climate:
    repo_token: 9986fd91b8a47246c65310a0a117cbee619c7620a3e2b6917a459e74328ab3f2

after_success:
  - vendor/bin/test-reporter

cache:
  directories:
    - node_modules
